Networks oauth feature
DanielYouCan/QnA pull request #10
Opened 2018-03-04 13:39 UTC by DanielYouCan

Implemented oauth authorization with facebook and twitter

2018-03-04 15:05 UTC, vkurennov requested changes

2018-03-04 15:05 UTC, vkurennov commented on app/controllers/application_controller.rb
> +  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_resource_not_found
Это бессмысленно, потому что в продакшене рельсы и так отображаютс страницу 404, а исключение выбрасывается только в дев- и тест- режимах

2018-03-04 15:05 UTC, vkurennov commented on app/controllers/omniauth_callbacks_controller.rb
> +    if @user.persisted? && @user.authorizations.by_provider(auth.provider, auth.uid).first.confirmed?
Очень некрасивый и длинный вызов во второй части условия, стоит сделать метод в модели User для этого.

2018-03-04 15:05 UTC, vkurennov commented on app/controllers/omniauth_callbacks_controller.rb
> +    elsif @user.persisted? && !@user.authorizations.by_provider(auth.provider, auth.uid).first.confirmed?
Вот тут как раз случай для вложенных if, тут они больше подходят. В начале проверяешь на `@user.persisted?, а во вложенном условии - на подтверждение авторизации. Так и более гибко  и читаемее и не нужно лишиние запросы делать

2018-03-04 15:05 UTC, vkurennov commented on app/controllers/users_controller.rb
> +  def flash_options
Делать валидацию в контроллере - так себе идея

2018-03-04 15:05 UTC, vkurennov commented on app/models/authorization.rb
> +    Authorization.transaction do
Здесь транзакция не нужна, т.к. ты только один объект изменяешь, и любое сохранение и так в транзакцию автоматом оборачивается. Ну и здесь лушче `update!` применить

2018-03-04 15:05 UTC, vkurennov commented on app/models/authorization.rb
> +    Authorization.transaction do
Опять не нужная транзакция. Транзакция нужна, когда ты обновляешьб одновременно несколько разных объектов.

2018-03-04 15:05 UTC, vkurennov commented on app/models/authorization.rb
> +      self.confirmation_token = SecureRandom.urlsafe_base64.to_s
Здесь тоже можно обойтись `update!`

2018-03-04 15:05 UTC, vkurennov commented on app/models/user.rb
> +    User.transaction do
Вот здесь транзакция оправдана, т.к. создается и юзер и авторизация для него

2018-03-04 15:05 UTC, vkurennov commented on spec/models/authorization_spec.rb
> +      expect(authorization.confirmed).to eq true
`expect(authorization).to be_confirmed`

2018-03-04 17:51 UTC, DanielYouCan commented on app/controllers/omniauth_callbacks_controller.rb
> -      redirect_to new_user_session_path, notice: "Confirm your email for signing in with #{kind}"
Или вот такой вариант лучше смотрится?
```
    if @user.new_record?
      session["devise.provider_data"] = request.env['omniauth.auth'].except("extra")
      redirect_to users_set_email_path
      return
    end

    if @user.has_confirmed_authorization?(auth.provider, auth.uid)
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: kind) if is_navigational_format?
    else
      redirect_to new_user_session_path, notice: "Confirm your email for signing in with #{kind}"
    end
```

2018-03-04 17:53 UTC, DanielYouCan commented on app/controllers/omniauth_callbacks_controller.rb
>        redirect_to users_set_email_path
Или вот такой вариант лучше смотрится?
```
    if @user.new_record?
      session["devise.provider_data"] = request.env['omniauth.auth'].except("extra")
      redirect_to users_set_email_path
      return
    end

    if @user.has_confirmed_authorization?(auth.provider, auth.uid)
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: kind) if is_navigational_format?
    else
      redirect_to new_user_session_path, notice: "Confirm your email for signing in with #{kind}"
    end
```

2018-03-05 08:21 UTC, vkurennov approved these changes

2018-03-05 08:21 UTC, vkurennov commented on app/models/authorization.rb
> +    self.update!(confirmation_token: nil)
Зачем 2 раза вызывать `update!`? Он же принимает хеш атрибутов, ты же в контроллере один раз вызываешь его и сразу все атрибуты в хеше передаешь. Вот и тут также.

2018-03-05 08:34 UTC, merged