Acceptance tests
DanielYouCan/QnA pull request #3
Opened 2018-02-10 10:18 UTC by DanielYouCan

2018-02-10 12:24 UTC, vkurennov requested changes

2018-02-10 12:24 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      flash.now[:warning] = 'Invalid attributes for answer'
А что рендерим? create.html? Зачем, когда можно question/show?

2018-02-10 12:24 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question = Question.new(question_params)
Лучше так: `@question = current_user.questions.new(...)`

2018-02-10 12:24 UTC, vkurennov commented on app/helpers/application_helper.rb
> +  def flash_class(key)
👍

2018-02-10 12:24 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +  - if user_signed_in? && current_user.is_author?(answer)
Тут можно применитьт [оператор safe navigation](http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/) и код станет проще: `if current_user&.is_author?(answer)`

2018-02-10 12:24 UTC, vkurennov commented on app/views/answers/_form.html.slim
> +    = f.text_field :body, id: :answer_body
Зачем вручную id элемента выставлять? рельсы это автоматом делают

2018-02-10 12:24 UTC, vkurennov commented on app/views/answers/create.html.slim
> +render 'form'
Плохое решение, почему юзер только форму должен увидеть? Он должен видеть всю страницу, с которой начал вводить ответ, т.е. страницу вопроса

2018-02-10 12:24 UTC, vkurennov commented on app/views/questions/new.html.slim
> +    = f.text_field :title, id: :question_title
Прекращай вручную id везде задавать, дай фремворку работать самостоятельно :-)

2018-02-10 12:24 UTC, vkurennov commented on app/views/questions/new.html.slim
> +    = f.text_field :body, id: :question_body
Опять не нужный id

2018-02-10 12:24 UTC, vkurennov commented on spec/acceptance/answers/create_answer_for_question_spec.rb
> +feature 'User adds answer to question', %q{
Нужен сценарий на ошибки валидации - проверить, что система выводит их пользователю.

2018-02-10 12:24 UTC, vkurennov commented on spec/acceptance/answers/create_answer_for_question_spec.rb
> +    expect(page).to have_content 'Answer was succefully added'
Нужно проверить наличие ответа на странице

2018-02-10 12:24 UTC, vkurennov commented on spec/acceptance/answers/delete_answer_spec.rb
> +  scenario 'User is not the aurhor of the answer' do
И такой же сценарий нужен для незалогиненного юзера

2018-02-10 12:24 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +feature 'User creates question', %q{
Нужен сценарий на ошибки валидации - проверить, что система выводит их пользователю.

2018-02-10 12:24 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +    expect(page).to have_content 'Your question was successfully created.'
Нужно проверить наличие заголовка и тела вопроса на странице

2018-02-10 12:24 UTC, vkurennov commented on spec/acceptance/questions/delete_my_question_spec.rb
> +  scenario 'User tries to delete someone else question' do
И такой же сценарий нужен для незалогиненного юзера

2018-02-10 12:24 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      context 'valid attributes' do
Нужно также проверить, что ответ связывается с залогиненным юзером

2018-02-10 12:24 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>      context 'with valid attributes' do
Нужно проверить, что вопрос связывается с залогиненным юзером

2018-02-10 12:24 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
А где тесты на метод #is_author?

2018-02-10 15:40 UTC, DanielYouCan commented on app/views/answers/_form.html.slim
> +    = f.text_field :body, id: :answer_body
Странно... У меня rails не делает это автоматически, и тесты не проходят из-за этого. Что-то нужно настроить для этого?

2018-02-10 16:17 UTC, DanielYouCan commented on app/controllers/answers_controller.rb
> +      flash.now[:warning] = 'Invalid attributes for answer'
Почему-то не проходит тест, если написать render 'questions/show'. А вот если в create сделать render 'questions/show' и в контроллере render :create, то все нормально

2018-02-11 11:36 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      flash.now[:warning] = 'Invalid attributes for answer'
Так а что ты в тесте протверяешь? То, что рендерится question/show или то, что рендерится  create?

2018-02-11 11:37 UTC, vkurennov commented on app/views/answers/_form.html.slim
> +    = f.text_field :body, id: :answer_body
Вообще, надо, чтобы fill_in работал по label, и по идее, рельсы все автоматом и должны выставить. Пришли в личку на форуме скриншот html, с этим элементом, если id убрать

2018-02-11 11:50 UTC, vkurennov approved these changes

2018-02-11 11:50 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      flash.now[:warning] = 'Invalid attributes for answer'
И этого не достаточно, нужно в самой форме выводить ошибки валидации

2018-02-11 11:50 UTC, vkurennov commented on app/views/questions/new.html.slim
> += form_with model: @question do |f|
Вот здесь нужно выводить ошибки валидации

2018-02-11 11:50 UTC, vkurennov commented on app/views/shared/_errors.html.slim
> +- if resource.present? && resource.errors.present?
Вот паршл вывода ошибок валидации. Теперь осталось его примениь в формах (он у тебя нигде не используется сейчас)

2018-02-11 11:50 UTC, vkurennov commented on spec/acceptance/answers/create_answer_for_question_spec.rb
> +    fill_in 'answer[body]', with: 'My unique answer'
Здесь нужно использовать метку поля, ту, которую. видит юзер

2018-02-11 11:50 UTC, vkurennov commented on spec/acceptance/answers/create_answer_for_question_spec.rb
> +    expect(page).to have_content question.answers.last.body
Лучше проверять именно тот текст, который ты указал в 17-й строке

2018-02-11 11:50 UTC, vkurennov commented on spec/acceptance/answers/create_answer_for_question_spec.rb
> +    expect(page).to have_content 'Invalid attributes for answer'
Нужно не флеш-сообщение из контроллера проверить, а сообщения об ошибках валидации

2018-02-11 11:50 UTC, vkurennov commented on spec/acceptance/answers/delete_answer_spec.rb
> +    expect(page).to_not have_content 'Delete answer'
Лучше have_link

2018-02-11 11:50 UTC, vkurennov commented on spec/acceptance/answers/delete_answer_spec.rb
> +    expect(page).to_not have_content 'Delete answer'
Лучше have_link

2018-02-11 11:50 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +    fill_in 'question[title]', with: 'Test question'
Опять же - используй видимые пользователю метки, а не атрибуты полей

2018-02-11 11:50 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +    expect(page).to have_content Question.last.title
Проверяй наличие того текста, который задаешь в поля, так надежнее. Потому что если `Question.last.title` вернет по какой-то причине nil, тест пройдет.

2018-02-11 11:50 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +    expect(page).to have_content 'Invalid attributes for a new question'
Нужно проверить вывод ошибок валидации, а не флеш-сообщения

2018-02-11 11:50 UTC, vkurennov commented on spec/acceptance/questions/delete_my_question_spec.rb
> +    expect(page).to_not have_content 'Delete question'
Лучше have_link

2018-02-11 11:50 UTC, vkurennov commented on spec/acceptance/questions/delete_my_question_spec.rb
> +    expect(page).to_not have_content 'Delete question'
Лучше have_link

2018-02-11 11:50 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect(Answer.last.user).to eq @user
А почему вдруг Answer.last? Ты уверен, что созданный ответ будет последним? а если поменяется сортировка в какой-то момент. В общем, такие вещи часто ведут к ложно-положительным тестам. Попробуй "добраться" до только что созданного ответа иным способом.

2018-02-11 11:50 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect(response).to render_template :create
Вот здесь попробуй написать `render_template 'questions/show'` и затем в контроллере поменяй, и проверь, пройдет ли тест.

2018-02-11 11:50 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect(Question.last.user).to eq @user
Опять же нужно по-другому это проверить. Можно тем же способом, что ты проверял связь вопроса и ответа в тестах AnswersController

2018-02-11 11:50 UTC, vkurennov commented on spec/models/user_spec.rb
> +      expect(user.is_author?(question)).to eq true
Есть более красивый синтаксис для методов-предикатов, их можно использовать как матчеры:

`expect(user).to be_is_author?(question)`

Правда, лучше название метода поменять тогда, например, на `author_of?`, а то как-то не красивая фраза получается

2018-02-11 11:50 UTC, vkurennov commented on spec/models/user_spec.rb
> +      expect(user.is_author?(answer)).to eq true
У тебя универсальный метод, ему без разницы, вопрос это или ответ, ему важно, чтобы у переданного объекта был метод `user_id`, поэтому не надо проверять на всех возможных типах аргумента, надо проверить на любом из них

2018-02-11 11:51 UTC, vkurennov requested changes
Случайно принял, хотел отклонить

2018-02-12 06:43 UTC, vkurennov approved these changes

2018-02-12 07:31 UTC, merged